import { Client } from "./types";

export const mockClients: Client[] = [
  {
    id: "1",
    slug: "k8x2m9",
    name: "María & Juan",
    eventType: "wedding",
    deadline: "2026-05-01",
    products: [
      { type: "digital", photoLimit: 20 },
      { type: "album", photoLimit: null, includesCover: true },
    ],
    isReady: false,
    digitalSelected: 14,
    albumSelected: 8,
    coverSelected: 1,
  },
  {
    id: "2",
    slug: "p3n7rz",
    name: "Ana Martínez",
    eventType: "quinceañera",
    deadline: "2026-05-15",
    products: [
      { type: "digital", photoLimit: 30 },
      { type: "album", photoLimit: null },
    ],
    isReady: false,
    digitalSelected: 22,
    albumSelected: 10,
    coverSelected: 0,
  },
  {
    id: "6",
    slug: "r4f9an",
    name: "Ana Martínez",
    eventType: "photobooth",
    deadline: "2026-07-12",
    products: [{ type: "digital", photoLimit: 40 }],
    isReady: false,
    digitalSelected: 5,
    albumSelected: 0,
    coverSelected: 0,
  },
  {
    id: "3",
    slug: "w5k1qb",
    name: "Studio Booth",
    eventType: "photobooth",
    deadline: null,
    products: [{ type: "digital", photoLimit: 50 }],
    isReady: false,
    digitalSelected: 0,
    albumSelected: 0,
    coverSelected: 0,
  },
  {
    id: "4",
    slug: "t9r4jy",
    name: "Laura & Marcos",
    eventType: "wedding",
    deadline: "2026-06-01",
    products: [
      { type: "digital", photoLimit: 25 },
      { type: "album", photoLimit: null, includesCover: true },
    ],
    isReady: true,
    digitalSelected: 25,
    albumSelected: 12,
    coverSelected: 2,
  },
  {
    id: "5",
    slug: "m2v8cq",
    name: "Diego Herrera",
    eventType: "birthday",
    deadline: "2026-04-30",
    products: [{ type: "digital", photoLimit: 15 }],
    isReady: true,
    digitalSelected: 15,
    albumSelected: 0,
    coverSelected: 0,
  },
];
