import { Client } from "./types";

export const mockClients: Client[] = [
  {
    id: "1",
    slug: "k8x2m9",
    name: "María & Juan",
    eventType: "wedding",
    deadline: "2026-05-01",
    photoLimit: 20,
    albumLimit: null,
    isReady: false,
    selected: 14,
  },
  {
    id: "2",
    slug: "p3n7rz",
    name: "Ana Martínez",
    eventType: "quinceañera",
    deadline: "2026-05-15",
    photoLimit: 30,
    albumLimit: null,
    isReady: false,
    selected: 22,
  },
  {
    id: "6",
    slug: "r4f9an",
    name: "Ana Martínez",
    eventType: "photobooth",
    deadline: "2026-07-12",
    photoLimit: 40,
    albumLimit: null,
    isReady: false,
    selected: 5,
  },
  {
    id: "3",
    slug: "w5k1qb",
    name: "Studio Booth",
    eventType: "photobooth",
    deadline: null,
    photoLimit: 50,
    albumLimit: null,
    isReady: false,
    selected: 0,
  },
  {
    id: "4",
    slug: "t9r4jy",
    name: "Laura & Marcos",
    eventType: "wedding",
    deadline: "2026-06-01",
    photoLimit: 25,
    albumLimit: null,
    isReady: true,
    selected: 25,
  },
  {
    id: "5",
    slug: "m2v8cq",
    name: "Diego Herrera",
    eventType: "birthday",
    deadline: "2026-04-30",
    photoLimit: 15,
    albumLimit: null,
    isReady: true,
    selected: 15,
  },
];
